"use strict";
(() => {
  const t=value=>window.PixelI18n?.t(value)||value;
  const bar=document.createElement('div');bar.className='feature-bar gif-feature-bar';document.querySelector('.gif-canvas-wrap').prepend(bar);
  const button=document.createElement('button');button.id='openAnimationStudio';button.textContent='画布 / 部件动画';bar.append(button);
  const importButton=document.createElement('button');importButton.textContent='导入图片';importButton.onclick=()=>document.querySelector('#gifImageInput').click();bar.append(importButton);
  const panel=document.createElement('dialog');panel.className='studio-dialog animation-dialog';
  panel.innerHTML=`<h2>部件动画工作区</h2><p>导入身体、头部等图层，在画面上拖动拼接。每个图层独立记录关键帧，未设关键帧的身体保持不动。</p>
  <div class="studio-actions"><label>画布宽 <input id="aw" type="number" min="1" max="2048" value="240"></label><label>画布高 <input id="ah" type="number" min="1" max="2048" value="240"></label><label>动作秒数 <input id="ad" type="number" min="0.01" max="60" step="0.01" value="1"></label><label>帧间隔秒 <input id="astep" type="number" min="0.01" max="1" step="0.01" value="0.1"></label><button id="aImport">导入部件图层</button><button id="aSource">添加所选素材为图层</button><select id="aSources" aria-label="可用素材"></select><input id="aFiles" type="file" accept="image/png,image/webp,image/jpeg" multiple hidden></div>
  <div class="studio-actions"><label>当前时间 <input id="at" type="number" min="0" step="0.01" value="0"></label><button id="aPlay">播放 / 停止</button><button id="aKey">记录 / 更新关键帧</button><button id="aDeleteKey">删除当前时间关键帧</button><button id="aPath">手绘运动路径：关</button><button id="aClearPath">清除运动路径</button></div>
  <div class="studio-work"><div class="studio-board"><canvas id="aCanvas" width="240" height="240"></canvas></div><div><label>图层（后面的在上层）<select id="aLayers" size="5"></select></label><div class="studio-actions"><button id="aCopy">复制图层</button><button id="aDelete">删除图层</button><button id="aUp">上移一层</button><button id="aDown">下移一层</button></div><div class="studio-actions"><label>X <input id="ax" type="number" value="0"></label><label>Y <input id="ay" type="number" value="0"></label><label>旋转角度 <input id="ar" type="number" value="0"></label><label>缩放 <input id="as" type="number" min="0.01" step="0.1" value="1"></label><label>不透明度 <input id="ao" type="number" min="0" max="1" step="0.1" value="1"></label></div><label>关键帧插值 <select id="ae"><option value="linear">线性</option><option value="ease">平滑缓入缓出</option><option value="sine">正弦缓动</option><option value="hold">保持（表情切换）</option><option value="bezier">自定义三次贝塞尔</option></select></label><div class="studio-actions"><label>控制点 1 X<input id="ab1" type="number" min="0" max="1" step="0.01" value="0.25"></label><label>控制点 1 Y<input id="ab2" type="number" step="0.01" value="0.1"></label><label>控制点 2 X<input id="ab3" type="number" min="0" max="1" step="0.01" value="0.25"></label><label>控制点 2 Y<input id="ab4" type="number" step="0.01" value="1"></label></div><p id="aKeys"></p></div></div>
  <p>手绘路径作用于当前图层中心，在整段动作内播放；位置路径优先于位置关键帧。旋转、缩放、不透明度仍由关键帧控制。画布外内容会被裁切。</p><div class="studio-actions"><button id="aBake">生成并追加到 GIF 时间线</button><button id="aClose">完成，返回 GIF</button></div>`;
  document.body.append(panel);const q=id=>panel.querySelector('#'+id),canvas=q('aCanvas');
  let scene={width:240,height:240,duration:1,step:.1,layers:[]},selected=-1,time=0,pathMode=false,drag=null,playing=0;
  const images=new Map();
  const uid=()=>crypto.randomUUID(); const layer=()=>scene.layers[selected];
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const num=(id,min,max,fallback)=>clamp(Number(q(id).value)||fallback,min,max);
  function changed(){state.project={...(state.project||{}),animationScene:structuredClone(scene)};markDirty();}
  function controls(){q('aw').value=scene.width;q('ah').value=scene.height;q('ad').value=scene.duration;q('astep').value=scene.step;}
  function loadImage(data){if(!images.has(data))images.set(data,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('图片无法读取'));im.src=data;}));return images.get(data);}
  function curve(t,l){if(l.ease==='hold')return 0;if(l.ease==='ease')return t*t*(3-2*t);if(l.ease==='sine')return (1-Math.cos(Math.PI*t))/2;if(l.ease!=='bezier')return t;const b=l.bezier||[.25,.1,.25,1], f=(u,p1,p2)=>3*(1-u)**2*u*p1+3*(1-u)*u*u*p2+u**3;let lo=0,hi=1;for(let i=0;i<24;i++){const m=(lo+hi)/2;if(f(m,b[0],b[2])<t)lo=m;else hi=m;}return f((lo+hi)/2,b[1],b[3]);}
  function pose(l,t){let p={x:l.x,y:l.y,r:l.r,s:l.s,o:l.o};const keys=l.keys||[];if(keys.length){if(t<=keys[0].t)p={...keys[0]};else if(t>=keys.at(-1).t)p={...keys.at(-1)};else {const i=keys.findIndex(k=>k.t>t),a=keys[i-1],b=keys[i],v=curve((t-a.t)/(b.t-a.t),l);for(const k of ['x','y','r','s','o'])p[k]=a[k]+(b[k]-a[k])*v;}}if(l.path?.length){const u=clamp(t/scene.duration,0,1)*(l.path.length-1),i=Math.floor(u),a=l.path[i],b=l.path[Math.min(i+1,l.path.length-1)];p.x=a.x+(b.x-a.x)*(u-i);p.y=a.y+(b.y-a.y)*(u-i);}p.s=Math.max(.01,p.s);p.o=clamp(p.o,0,1);return p;}
  async function render(target,t,overlay=false){const ctx=target.getContext('2d');target.width=scene.width;target.height=scene.height;ctx.imageSmoothingEnabled=false;for(const l of scene.layers){const im=await loadImage(l.data),p=pose(l,t);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.r*Math.PI/180);ctx.scale(p.s,p.s);ctx.globalAlpha=p.o;ctx.drawImage(im,-l.width/2,-l.height/2);ctx.restore();}if(overlay&&layer()){const p=pose(layer(),t);ctx.strokeStyle='#00cbb4';ctx.lineWidth=1;ctx.strokeRect(p.x-5,p.y-5,10,10);if(layer().path?.length){ctx.beginPath();layer().path.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();}}}
  let rendering=false,rerender=false;async function draw(){if(rendering){rerender=true;return;}rendering=true;do{rerender=false;try{await render(canvas,time,true);}catch(e){toast(e.message,'error');}}while(rerender);rendering=false;}
  function fields(){const l=layer();if(!l)return;const p=pose(l,time);for(const k of ['x','y','r','s','o'])q('a'+k).value=Number(p[k].toFixed(3));q('ae').value=l.ease;[1,2,3,4].forEach((n,i)=>q('ab'+n).value=l.bezier[i]);q('aKeys').textContent=t('关键帧：')+l.keys.map(k=>k.t.toFixed(2)+'s').join(' · ');}
  function list(){q('aLayers').replaceChildren();scene.layers.forEach((l,i)=>{const o=new Option(l.name,String(i));q('aLayers').add(o);});q('aLayers').value=String(selected);fields();draw();}
  button.onclick=()=>{scene=structuredClone(state.project?.animationScene||scene);selected=scene.layers.length?0:-1;controls();q('aSources').replaceChildren();[...state.availableFrames,...state.frames].forEach((f,i)=>q('aSources').add(new Option(f.name,String(i))));panel.showModal();list();};
  q('aClose').onclick=()=>{stop();changed();panel.close();};panel.addEventListener('cancel',()=>{stop();changed();});
  function stop(){cancelAnimationFrame(playing);playing=0;}
  async function add(f){await loadImage(f.data);scene.layers.push({id:uid(),name:f.name,data:f.data,width:f.width,height:f.height,x:scene.width/2,y:scene.height/2,r:0,s:1,o:1,ease:'linear',bezier:[.25,.1,.25,1],keys:[],path:[]});selected=scene.layers.length-1;changed();list();}
  q('aImport').onclick=()=>q('aFiles').click();q('aFiles').onchange=async e=>{try{for(const f of e.target.files){const data=await new Promise((r,j)=>{const reader=new FileReader();reader.onload=()=>r(reader.result);reader.onerror=j;reader.readAsDataURL(f);});const im=await loadImage(data);await add({name:f.name,data,width:im.width,height:im.height});}}catch{toast('部件导入失败。','error');}e.target.value='';};
  q('aSource').onclick=()=>{const f=[...state.availableFrames,...state.frames][Number(q('aSources').value)];if(f)void add(f);};
  for(const id of ['aw','ah','ad','astep'])q(id).onchange=()=>{scene.width=Math.round(num('aw',1,2048,240));scene.height=Math.round(num('ah',1,2048,240));scene.duration=num('ad',.01,60,1);scene.step=num('astep',.01,1,.1);time=Math.min(time,scene.duration);q('at').value=time;controls();changed();draw();};
  q('aLayers').onchange=()=>{selected=Number(q('aLayers').value);fields();draw();};
  q('at').onchange=()=>{stop();time=num('at',0,scene.duration,0);q('at').value=time;fields();draw();};
  function setPose(){const l=layer();if(!l)return;const p={t:time,x:num('ax',-10000,10000,0),y:num('ay',-10000,10000,0),r:num('ar',-36000,36000,0),s:num('as',.01,100,1),o:clamp(Number(q('ao').value),0,1)};if(l.keys.length){l.keys=l.keys.filter(k=>Math.abs(k.t-time)>.004);l.keys.push(p);l.keys.sort((a,b)=>a.t-b.t);}else Object.assign(l,p);changed();draw();}
  for(const k of ['x','y','r','s','o'])q('a'+k).onchange=setPose;
  q('aKey').onclick=()=>{const l=layer();if(!l)return;const p=pose(l,time);l.keys=l.keys.filter(k=>Math.abs(k.t-time)>.004);l.keys.push({...p,t:time});l.keys.sort((a,b)=>a.t-b.t);changed();fields();};
  q('aDeleteKey').onclick=()=>{if(!layer())return;layer().keys=layer().keys.filter(k=>Math.abs(k.t-time)>.004);changed();fields();draw();};
  for(const id of ['ae','ab1','ab2','ab3','ab4'])q(id).onchange=()=>{if(!layer())return;layer().ease=q('ae').value;layer().bezier=[num('ab1',0,1,.25),Number(q('ab2').value)||0,num('ab3',0,1,.25),Number(q('ab4').value)||0];changed();draw();};
  q('aCopy').onclick=()=>{if(!layer())return;scene.layers.push({...structuredClone(layer()),id:uid(),name:layer().name+' 副本'});selected=scene.layers.length-1;changed();list();};
  q('aDelete').onclick=()=>{if(!layer())return;scene.layers.splice(selected,1);selected=Math.min(selected,scene.layers.length-1);changed();list();};
  for(const [id,d] of [['aUp',1],['aDown',-1]])q(id).onclick=()=>{const n=selected+d;if(n<0||n>=scene.layers.length)return;[scene.layers[selected],scene.layers[n]]=[scene.layers[n],scene.layers[selected]];selected=n;changed();list();};
  q('aPath').onclick=()=>{pathMode=!pathMode;q('aPath').textContent=t('手绘运动路径：'+(pathMode?'开':'关'));};q('aClearPath').onclick=()=>{if(layer()){layer().path=[];changed();draw();}};
  const point=e=>{const b=canvas.getBoundingClientRect();return{x:(e.clientX-b.left)*scene.width/b.width,y:(e.clientY-b.top)*scene.height/b.height};};
  canvas.onpointerdown=e=>{if(!layer())return;stop();canvas.setPointerCapture(e.pointerId);const p=point(e),v=pose(layer(),time);drag={x:p.x-v.x,y:p.y-v.y};if(pathMode)layer().path=[p];};
  canvas.onpointermove=e=>{if(!drag||!layer())return;const p=point(e);if(pathMode){if(layer().path.length<2000)layer().path.push(p);draw();}else{q('ax').value=Math.round(p.x-drag.x);q('ay').value=Math.round(p.y-drag.y);setPose();}};
  canvas.onpointerup=canvas.onpointercancel=()=>{if(drag){drag=null;changed();fields();draw();}};
  q('aPlay').onclick=()=>{if(playing){stop();return;}const start=performance.now();const tick=now=>{time=((now-start)/1000)%scene.duration;q('at').value=time.toFixed(2);draw();playing=requestAnimationFrame(tick);};playing=requestAnimationFrame(tick);};
  q('aBake').onclick=async()=>{if(!scene.layers.length)return toast('请先添加部件图层。');const count=Math.ceil(scene.duration/scene.step);if(count>600||scene.width*scene.height*count>80000000)return toast('动作过大，请减小画布或提高帧间隔（最多 600 帧）。','error');stop();q('aBake').disabled=true;try{const frames=[];for(let i=0;i<count;i++){const c=document.createElement('canvas');await render(c,i*scene.step);frames.push({id:uid(),name:'合成_'+String(i+1).padStart(3,'0'),data:c.toDataURL(),width:scene.width,height:scene.height,duration:Math.round(Math.min(scene.step,scene.duration-i*scene.step)*100)/100});}state.frames.push(...frames);state.selected=state.frames.length-frames.length;changed();persistDraft();refreshUI();panel.close();toast(`已追加 ${count} 帧合成动画。`);}catch(e){toast(e.message,'error');}finally{q('aBake').disabled=false;}};
})();
