"use strict";
(() => {
 const t=s=>PixelI18n.t(s),stage=document.querySelector('#paintStage');
 const host=document.createElement('details');host.className='layer-panel';host.id='drawingLayers';
 host.innerHTML=`<summary><i data-lucide="layers"></i> <span>图层与画笔</span></summary><div class="drawing-controls">
 <div class="drawing-tool-grid"><button data-studio-tool="smooth"><i data-lucide="brush"></i><span>圆头画笔</span></button><button data-studio-tool="soft"><i data-lucide="paintbrush"></i><span>柔边画笔</span></button><button data-studio-tool="smooth-eraser"><i data-lucide="eraser"></i><span>柔绘橡皮</span></button><button data-studio-tool="text"><i data-lucide="type"></i><span>文字</span></button></div>
 <div class="studio-actions"><label>笔刷大小 <input id="studioBrush" type="number" min="1" max="256" value="8"></label><label>不透明度 <input id="studioOpacity" type="number" min="1" max="100" value="100">%</label><label><input id="studioPressure" type="checkbox" checked> 压感</label></div>
 <label>文字内容 <input id="studioText" type="text" maxlength="500" placeholder="Text"></label>
 <div class="studio-actions"><button id="layerAdd"><i data-lucide="plus"></i><span>新建图层</span></button><button id="layerImport"><i data-lucide="image-plus"></i><span>导入图层</span></button><button id="layerDuplicate"><i data-lucide="copy"></i><span>复制图层</span></button><button id="layerDelete"><i data-lucide="trash-2"></i><span>删除图层</span></button></div>
 <div id="layerList"></div><div class="studio-actions"><button id="layerUp"><i data-lucide="arrow-up"></i><span>上移一层</span></button><button id="layerDown"><i data-lucide="arrow-down"></i><span>下移一层</span></button><button id="layerMerge"><i data-lucide="combine"></i><span>向下合并</span></button></div>
 <div class="studio-actions"><label>图层名称 <input id="layerName" maxlength="80"></label><label>图层不透明度 <input id="layerOpacity" type="number" min="0" max="100" value="100">%</label></div>
 <div class="studio-actions"><button id="drawingPlay"><i data-lucide="play"></i><span>播放 / 停止</span></button><label>帧时长 <input id="drawingDuration" type="number" min="0.01" max="60" step="0.01" value="0.12"></label><button id="drawingFrameLeft"><i data-lucide="arrow-left"></i><span>前移帧</span></button><button id="drawingFrameRight"><i data-lucide="arrow-right"></i><span>后移帧</span></button><label><input id="drawingOnion" type="checkbox"> 洋葱皮</label></div>
 <input id="layerFile" type="file" accept="image/*" hidden></div>`;
 const q=id=>host.querySelector('#'+id);let busy=false,timer=0,stroke=null;
 // The tools occupy layout space rather than covering the drawing surface.
 document.addEventListener('DOMContentLoaded',()=>{document.querySelector('.paint-editor>.feature-bar').append(host);render();PixelI18n.apply();window.lucide?.createIcons();});
 function render(){const f=currentFrame();if(!f)return;const layers=PixelLayers.ensure(f);q('layerList').replaceChildren();
  [...layers].reverse().forEach(layer=>{const index=layers.indexOf(layer),row=document.createElement('div');row.className='layer-row'+(index===f.activeLayer?' selected':'');
   const thumb=document.createElement('img');thumb.src=layer.data;thumb.alt='';
   const select=document.createElement('button');select.textContent=layer.name;select.onclick=async()=>{if(busy||state.drawing)return;commitCanvas();f.activeLayer=index;await renderCurrentFrame();render();};
   const visible=document.createElement('button');visible.innerHTML=`<i data-lucide="${layer.visible?'eye':'eye-off'}"></i>`;visible.title=t('显示图层');visible.setAttribute('aria-label',t('显示图层'));visible.setAttribute('aria-pressed',String(layer.visible));visible.onclick=()=>mutate(()=>layer.visible=!layer.visible);
   const lock=document.createElement('button');lock.innerHTML=`<i data-lucide="${layer.locked?'lock':'lock-open'}"></i>`;lock.setAttribute('aria-label',t('锁定图层'));lock.setAttribute('aria-pressed',String(layer.locked));lock.onclick=()=>mutate(()=>layer.locked=!layer.locked);
   row.append(thumb,select,visible,lock);q('layerList').append(row);
  });q('layerName').value=PixelLayers.active(f).name;q('layerOpacity').value=Math.round(PixelLayers.active(f).opacity*100);q('drawingDuration').value=f.duration||.12;window.lucide?.createIcons();
 }
 async function mutate(action){if(busy||state.drawing||stroke)return;busy=true;try{pushHistory();await action();await renderCurrentFrame();commitCanvas();render();}finally{busy=false;}}
 const blank=()=>{const c=document.createElement('canvas');c.width=currentFrame().width;c.height=currentFrame().height;return c.toDataURL();};
 q('layerAdd').onclick=()=>mutate(()=>{const f=currentFrame();f.layers.push(PixelLayers.make(blank(),'Layer '+(f.layers.length+1)));f.activeLayer=f.layers.length-1;});
 q('layerDuplicate').onclick=()=>mutate(()=>{const f=currentFrame();f.layers.splice(f.activeLayer+1,0,{...structuredClone(PixelLayers.active(f)),id:crypto.randomUUID(),name:PixelLayers.active(f).name+' copy'});f.activeLayer++;});
 q('layerDelete').onclick=()=>mutate(()=>{const f=currentFrame();f.layers.splice(f.activeLayer,1);if(!f.layers.length)f.layers=[PixelLayers.make(blank())];f.activeLayer=Math.min(f.activeLayer,f.layers.length-1);});
 for(const [id,delta] of [['layerUp',1],['layerDown',-1]])q(id).onclick=()=>{const f=currentFrame(),next=f.activeLayer+delta;if(next<0||next>=f.layers.length)return;void mutate(()=>{[f.layers[next],f.layers[f.activeLayer]]=[f.layers[f.activeLayer],f.layers[next]];f.activeLayer=next;});};
 q('layerMerge').onclick=()=>{const f=currentFrame(),i=f.activeLayer;if(i<1||!f.layers[i].visible||!f.layers[i-1].visible||f.layers[i-1].locked)return;void mutate(async()=>{const c=document.createElement('canvas');c.width=f.width;c.height=f.height;const ctx=c.getContext('2d');for(const l of [f.layers[i-1],f.layers[i]]){ctx.globalAlpha=l.opacity;ctx.drawImage(await PixelLayers.image(l.data),0,0);}f.layers[i-1].data=c.toDataURL();f.layers[i-1].opacity=1;f.layers.splice(i,1);f.activeLayer--;});};
 q('layerName').onchange=()=>mutate(()=>PixelLayers.active(currentFrame()).name=q('layerName').value.trim()||'Layer');
 q('layerOpacity').onchange=()=>mutate(()=>PixelLayers.active(currentFrame()).opacity=Math.max(0,Math.min(100,Number(q('layerOpacity').value)||0))/100);
 q('layerImport').onclick=()=>q('layerFile').click();q('layerFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});await PixelLayers.image(data);await mutate(()=>{const f=currentFrame();f.layers.push(PixelLayers.make(data,file.name));f.activeLayer=f.layers.length-1;});}catch{toast(t('图片无法读取'),'error');}e.target.value='';};
 q('drawingDuration').onchange=()=>{currentFrame().duration=Math.max(.01,Math.min(60,Number(q('drawingDuration').value)||.12));markDirty();};
 for(const [id,delta] of [['drawingFrameLeft',-1],['drawingFrameRight',1]])q(id).onclick=()=>{const n=state.selected+delta;if(n<0||n>=state.frames.length)return;pushFrameActionHistory();[state.frames[n],state.frames[state.selected]]=[state.frames[state.selected],state.frames[n]];selectFrame(n);markDirty();};
 function stop(){clearTimeout(timer);timer=0;}q('drawingPlay').onclick=()=>{if(timer){stop();return;}const next=()=>{selectFrame((state.selected+1)%state.frames.length);timer=setTimeout(next,(currentFrame().duration||.12)*1000);};timer=setTimeout(next,(currentFrame().duration||.12)*1000);};
 const onion=document.createElement('canvas');onion.id='paintOnion';onion.style.cssText='position:absolute;inset:0;width:100%;height:100%;opacity:.22;pointer-events:none;image-rendering:pixelated';paintCanvas.before(onion);
 async function onionRender(){onion.width=paintCanvas.width;onion.height=paintCanvas.height;if(q('drawingOnion').checked&&state.selected>0){const previous=state.frames[state.selected-1];const image=await PixelLayers.image(previous.data);onion.getContext('2d').drawImage(image,0,0);}}
 q('drawingOnion').onchange=onionRender;window.addEventListener('paint-layers-change',()=>{render();void onionRender();});
 host.querySelectorAll('[data-studio-tool]').forEach(b=>b.onclick=()=>{document.querySelector('[data-tool="pencil"]').click();setTool(b.dataset.studioTool);host.querySelectorAll('[data-studio-tool]').forEach(x=>x.classList.toggle('active',x===b));});
 const point=e=>{const b=paintCanvas.getBoundingClientRect();return {x:(e.clientX-b.left)*paintCanvas.width/b.width,y:(e.clientY-b.top)*paintCanvas.height/b.height};};
 const consume=e=>{e.preventDefault();e.stopImmediatePropagation();};
 function draw(a,b,e){paintContext.save();paintContext.globalAlpha=Math.max(.01,Math.min(1,Number(q('studioOpacity').value)/100));const size=Math.max(1,Math.min(256,Number(q('studioBrush').value)||8))*(q('studioPressure').checked&&e.pointerType==='pen'?Math.max(.1,e.pressure):1);paintContext.strokeStyle=state.color;paintContext.fillStyle=state.color;paintContext.lineWidth=size;paintContext.lineCap='round';paintContext.lineJoin='round';if(state.tool==='smooth-eraser')paintContext.globalCompositeOperation='destination-out';if(state.tool==='soft'){paintContext.shadowColor=state.color;paintContext.shadowBlur=size/2;}paintContext.beginPath();paintContext.moveTo(a.x,a.y);paintContext.lineTo(b.x+.001,b.y+.001);paintContext.stroke();paintContext.restore();schedulePaintComposite();}
 stage.addEventListener('pointerdown',e=>{if(state.panMode)return;if(!editableLayer()){consume(e);return;}if(!['smooth','soft','smooth-eraser','text'].includes(state.tool))return;consume(e);if(e.button!==0)return;stop();pushHistory();const p=point(e);if(state.tool==='text'){paintContext.save();paintContext.font=Math.max(8,Math.min(256,Number(q('studioBrush').value)||16))+'px sans-serif';paintContext.fillStyle=state.color;paintContext.globalAlpha=Number(q('studioOpacity').value)/100;paintContext.fillText(q('studioText').value,p.x,p.y);paintContext.restore();commitCanvas();return;}stroke={id:e.pointerId,last:p};stage.setPointerCapture(e.pointerId);draw(p,p,e);},true);
 stage.addEventListener('pointermove',e=>{if(!stroke||stroke.id!==e.pointerId)return;consume(e);const samples=e.getCoalescedEvents?.();for(const sample of samples?.length?samples:[e]){const p=point(sample);draw(stroke.last,p,sample);stroke.last=p;}},true);
 for(const type of ['pointerup','pointercancel'])stage.addEventListener(type,e=>{if(!stroke||stroke.id!==e.pointerId)return;consume(e);stroke=null;commitCanvas();releasePaintPointer(e.pointerId);},true);
})();
