"use strict";
(() => {
  const labels={en:['Drawing tools','Line','Rectangle','Ellipse','Select / move','Filled shapes','Mirror X','Mirror Y','Brush size','Opacity','Pixel grid','Copy selection','Paste','Delete selection','Flip horizontally','Flip vertically','Rotate 90°','Select all','Clear selection','Close','Drag to draw or select. Drag inside a selection to move it.'],ja:['描画ツール','直線','四角形','楕円','選択・移動','図形を塗りつぶす','左右対称','上下対称','ブラシサイズ','不透明度','ピクセルグリッド','選択範囲をコピー','貼り付け','選択範囲を消去','左右反転','上下反転','90度回転','すべて選択','選択解除','閉じる','ドラッグで描画・選択。選択範囲の内側をドラッグすると移動できます。'],'zh-CN':['绘画工具','直线','矩形','椭圆','选区 / 移动','实心图形','左右镜像','上下镜像','笔刷大小','不透明度','像素网格','复制选区','粘贴','清除选区像素','水平翻转','垂直翻转','旋转90度','全选','取消选区','关闭','拖动绘制或框选，在选区内部拖动可移动像素。']};
  const t=i=>(labels[window.PixelI18n?.language()]||labels['zh-CN'])[i];
  let tool=null,selection=null,clipboard=null,stroke=null,filled=false,mx=false,my=false,opacity=1;
  const stage=document.querySelector('#paintStage');
  const bar=document.createElement('div');bar.className='feature-bar';document.querySelector('.paint-editor .workspace').before(bar);
  const launcher=document.createElement('button');launcher.className='paint-more';launcher.textContent=t(0);bar.append(launcher);
  const quick=[];['line','rect','ellipse','select'].forEach((v,i)=>{const b=document.createElement('button');b.textContent=t(i+1);b.onclick=()=>{tool=v;setTool('pencil');launcher.textContent=t(0);quick.forEach(x=>x.classList.toggle('active',x===b));};quick.push(b);bar.append(b);});
  const dialog=document.createElement('section');dialog.className='inline-paint-tools';dialog.hidden=true;bar.append(dialog);dialog.close=()=>{dialog.hidden=true;dialog.open=false;};dialog.showModal=()=>{dialog.hidden=false;dialog.open=true;const layers=document.querySelector('#drawingLayers');if(layers)layers.open=false;};
  const overlay=document.createElement('div');overlay.style.cssText='position:absolute;pointer-events:none;border:1px dashed #ffad50;box-sizing:border-box;display:none;z-index:3';stage.append(overlay);
  function bounds(){if(!selection){overlay.style.display='none';return;}const b=paintCanvas.getBoundingClientRect(),a=stage.getBoundingClientRect(),sx=b.width/paintCanvas.width,sy=b.height/paintCanvas.height;Object.assign(overlay.style,{display:'block',left:(b.left-a.left+selection.x*sx)+'px',top:(b.top-a.top+selection.y*sy)+'px',width:selection.w*sx+'px',height:selection.h*sy+'px'});}
  new ResizeObserver(()=>{bounds();const b=paintCanvas.getBoundingClientRect();stage.style.setProperty('--pixel-x',(b.width/paintCanvas.width)+'px');stage.style.setProperty('--pixel-y',(b.height/paintCanvas.height)+'px');}).observe(paintCanvas);
  function action(name,fn){const b=document.createElement('button');b.textContent=name;b.onclick=fn;return b;}
  function menu(){dialog.replaceChildren();const h=document.createElement('h2');h.textContent=t(0);dialog.append(h);const tools=document.createElement('div');tools.className='studio-actions';['line','rect','ellipse','select'].forEach((v,i)=>tools.append(action(t(i+1),()=>{tool=v;setTool('pencil');launcher.textContent=t(i+1);dialog.close();})));dialog.append(tools);
    const check=(i,value,fn)=>{const l=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.checked=value;c.onchange=()=>fn(c.checked);l.append(c,document.createTextNode(t(i)));dialog.append(l);};
    check(5,filled,v=>filled=v);check(6,mx,v=>mx=v);check(7,my,v=>my=v);check(10,stage.classList.contains('pixel-grid'),v=>stage.classList.toggle('pixel-grid',v));
    for(const [i,v,min,max,step,fn] of [[8,state.brush,1,64,1,v=>{state.brush=v;document.querySelector('#brushReadout').value=v+' px';}],[9,opacity,0.01,1,.01,v=>opacity=v]]){const l=document.createElement('label'),input=document.createElement('input');input.type='number';input.value=v;input.min=min;input.max=max;input.step=step;input.onchange=()=>fn(Math.max(min,Math.min(max,Number(input.value)||min)));l.append(document.createTextNode(t(i)+' '),input);dialog.append(l);}
    const row=document.createElement('div');row.className='studio-actions';[[11,copy],[12,paste],[13,erase],[14,()=>transform('x')],[15,()=>transform('y')],[16,()=>transform('rotate')],[17,()=>{selection={x:0,y:0,w:paintCanvas.width,h:paintCanvas.height};tool='select';bounds();}],[18,()=>{selection=null;bounds();}]].forEach(([i,f])=>row.append(action(t(i),()=>{f();dialog.close();})));dialog.append(row);const p=document.createElement('p');p.textContent=t(20);dialog.append(p,action(t(19),()=>dialog.close()));}
  launcher.onclick=()=>{if(dialog.open){dialog.close();return;}menu();dialog.showModal();};
  document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{tool=null;selection=null;bounds();launcher.textContent=t(0);}));
  const rawPoint=paintPoint;paintPoint=(x,y)=>{paintContext.save();paintContext.globalAlpha=opacity;const points=[[x,y]];if(mx)points.push([paintCanvas.width-1-x,y]);if(my)points.push([x,paintCanvas.height-1-y]);if(mx&&my)points.push([paintCanvas.width-1-x,paintCanvas.height-1-y]);for(const [a,b] of points)if(!selection||(a>=selection.x&&a<selection.x+selection.w&&b>=selection.y&&b<selection.y+selection.h))rawPoint(a,b);paintContext.restore();};
  const rect=(a,b)=>({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x)+1,h:Math.abs(a.y-b.y)+1});
  function shape(a,b){if(tool==='line'){drawLine(a,b);return;}const r=rect(a,b);if(tool==='rect'){for(let y=r.y;y<r.y+r.h;y++)for(let x=r.x;x<r.x+r.w;x++)if(filled||x===r.x||x===r.x+r.w-1||y===r.y||y===r.y+r.h-1)paintPoint(x,y);return;}const cx=r.x+(r.w-1)/2,cy=r.y+(r.h-1)/2,rx=r.w/2,ry=r.h/2;const inside=(x,y)=>((x-cx)/rx)**2+((y-cy)/ry)**2<=1;for(let y=r.y;y<r.y+r.h;y++)for(let x=r.x;x<r.x+r.w;x++)if(inside(x,y)&&(filled||!inside(x-1,y)||!inside(x+1,y)||!inside(x,y-1)||!inside(x,y+1)))paintPoint(x,y);}
  function snapshot(){return paintContext.getImageData(0,0,paintCanvas.width,paintCanvas.height);}
  function restore(){paintContext.putImageData(stroke.image,0,0);schedulePaintComposite();}
  function consume(e){e.preventDefault();e.stopImmediatePropagation();}
  stage.addEventListener('pointerdown',e=>{if(!tool||state.panMode||!currentFrame()||e.button!==0)return;consume(e);if(stroke){restore();stroke=null;return;}const p=canvasPoint(e);const moving=tool==='select'&&selection&&p.x>=selection.x&&p.y>=selection.y&&p.x<selection.x+selection.w&&p.y<selection.y+selection.h;stroke={id:e.pointerId,start:p,image:snapshot(),moving,original:selection?{...selection}:null};if(moving)stroke.pixels=paintContext.getImageData(selection.x,selection.y,selection.w,selection.h);if(tool!=='select'||moving)pushHistory();stage.setPointerCapture(e.pointerId);},true);
  stage.addEventListener('pointermove',e=>{if(!stroke||stroke.id!==e.pointerId)return;consume(e);const p=canvasPoint(e);if(tool==='select'){if(stroke.moving){restore();const r=stroke.original;paintContext.clearRect(r.x,r.y,r.w,r.h);selection={...r,x:Math.max(0,Math.min(paintCanvas.width-r.w,r.x+p.x-stroke.start.x)),y:Math.max(0,Math.min(paintCanvas.height-r.h,r.y+p.y-stroke.start.y))};paintContext.putImageData(stroke.pixels,selection.x,selection.y);}else selection=rect(stroke.start,p);bounds();}else{restore();shape(stroke.start,p);}},true);
  const finish=e=>{if(!stroke||stroke.id!==e.pointerId)return;consume(e);if(e.type==='pointercancel')restore();else if(tool!=='select'||stroke.moving){if(tool!=='select'){restore();shape(stroke.start,canvasPoint(e));}commitCanvas();}stroke=null;releasePaintPointer(e.pointerId);bounds();};stage.addEventListener('pointerup',finish,true);stage.addEventListener('pointercancel',finish,true);
  function copy(){const r=selection||{x:0,y:0,w:paintCanvas.width,h:paintCanvas.height};clipboard=paintContext.getImageData(r.x,r.y,r.w,r.h);}
  function paste(){if(!clipboard||!editableLayer())return;pushHistory();const c=document.createElement('canvas');c.width=clipboard.width;c.height=clipboard.height;c.getContext('2d').putImageData(clipboard,0,0);const x=selection?.x||0,y=selection?.y||0;paintContext.drawImage(c,x,y);selection={x,y,w:Math.min(c.width,paintCanvas.width-x),h:Math.min(c.height,paintCanvas.height-y)};tool='select';commitCanvas();bounds();}
  function erase(){if(!selection||!editableLayer())return;pushHistory();paintContext.clearRect(selection.x,selection.y,selection.w,selection.h);commitCanvas();}
  function transform(kind){const r=selection||{x:0,y:0,w:paintCanvas.width,h:paintCanvas.height},c=document.createElement('canvas');c.width=r.w;c.height=r.h;c.getContext('2d').putImageData(paintContext.getImageData(r.x,r.y,r.w,r.h),0,0);pushHistory();paintContext.clearRect(r.x,r.y,r.w,r.h);paintContext.save();paintContext.translate(r.x+r.w/2,r.y+r.h/2);if(kind==='rotate')paintContext.rotate(Math.PI/2);else paintContext.scale(kind==='x'?-1:1,kind==='y'?-1:1);paintContext.imageSmoothingEnabled=false;paintContext.drawImage(c,-r.w/2,-r.h/2);paintContext.restore();commitCanvas();}
  document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select')||dialog.open)return;if(e.key==='Escape'){selection=null;tool=null;bounds();}if((e.ctrlKey||e.metaKey)&&['c','v','a'].includes(e.key.toLowerCase())){e.preventDefault();if(e.key.toLowerCase()==='c')copy();if(e.key.toLowerCase()==='v')paste();if(e.key.toLowerCase()==='a'){selection={x:0,y:0,w:paintCanvas.width,h:paintCanvas.height};tool='select';bounds();}}if(e.key==='Delete'&&selection){e.preventDefault();erase();}});
  const oldRefresh=refreshUI;refreshUI=(...args)=>{selection=null;stroke=null;bounds();return oldRefresh(...args);};
  document.addEventListener('pixel-decomposer-language',()=>{launcher.textContent=t(0);quick.forEach((b,i)=>b.textContent=t(i+1));if(dialog.open)menu();});
})();
